# Stage 1: Build Astro
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps
COPY . .
ENV IS_DOCKER=true
RUN npm run build

# Stage 2: Production Runner
FROM node:22-alpine AS runner
WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production --legacy-peer-deps
COPY --from=builder /app/dist ./dist

EXPOSE 4321
ENV HOST=0.0.0.0
ENV PORT=4321
ENV IS_DOCKER=true

CMD ["node", "./dist/server/entry.mjs"]
