# Stage 1: Build Strapi
FROM node:20-alpine AS builder
# Install dependencies for compiling native node modules
RUN apk add --no-cache build-base gcc autoconf automake libtool zlib-dev libpng-dev nasm bash python3
WORKDIR /app
COPY backend/package*.json ./
RUN npm ci
COPY backend/ ./
RUN npm run build

# Stage 2: Production Runner
FROM node:20-alpine AS runner
RUN apk add --no-cache libpng libjpeg-turbo-dev
WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/public ./public
COPY --from=builder /app/tsconfig.json ./tsconfig.json



EXPOSE 1337
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=1337

CMD ["npm", "run", "start"]
